version: '3.7'

services:
  api:
    build: .
    ports:
      - 5002:80
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: My-Secret-123
    ports:
      - 1433:1433
