version: '3.1'

services:
  app:
    build: .
    ports:
      - 5000:80
    depends_on:
      - db
  
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: My-Secret-123
    ports:
      - 1433:1433
